sudo: required
services:
  - docker

before_install:
  - docker build -t ledebardeur/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ledebardeur/react-test npm run test

after_success:
  - docker build -t ledebardeur/multi-client ./client
  - docker build -t ledebardeur/multi-server ./server
  - docker build -t ledebardeur/multi-nginx ./nginx
  - docker build -t ledebardeur/multi-worker ./worker
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_ID}" --password-stdin
  - docker push ledebardeur/multi-client
  - docker push ledebardeur/multi-server
  - docker push ledebardeur/multi-nginx
  - docker push ledebardeur/multi-worker

deploy:
  provider: elasticbeanstalk
  edge: true
  region: eu-west-3
  app: multi-docker
  env: MultiDocker-env
  bucket_name: "elasticbeanstalk-eu-west-3-907518596288"
  bucket_path : "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_KEY